# Generated by Django 5.1.3 on 2024-11-29 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='img',
            field=models.ImageField(default=111, upload_to='judge/'),
            preserve_default=False,
        ),
    ]
