# Generated by Django 5.1.3 on 2024-11-26 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('admission_no', models.IntegerField()),
                ('student_cls', models.IntegerField()),
                ('division', models.CharField(max_length=30)),
                ('status', models.CharField(default='active', max_length=100)),
                ('added_date', models.DateField(auto_now_add=True)),
            ],
            options={
                'db_table': 'participant',
            },
        ),
    ]
