# Generated by Django 5.1.3 on 2024-11-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0002_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='status',
        ),
    ]
