# Generated by Django 5.1.3 on 2024-11-26 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0004_participant_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='category',
            field=models.CharField(default='Category-1', max_length=30),
        ),
        migrations.AlterField(
            model_name='participant',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
