# Generated by Django 5.1.3 on 2024-11-26 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0006_participant_code_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubrics1', models.FloatField()),
                ('rubrics2', models.FloatField()),
                ('rubrics3', models.FloatField()),
                ('rubrics4', models.FloatField()),
                ('rubrics5', models.FloatField()),
                ('rubrics6', models.FloatField()),
                ('rubrics7', models.FloatField()),
                ('comments', models.CharField(max_length=200)),
                ('total', models.FloatField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alif_admin.participant')),
            ],
            options={
                'db_table': 'score',
            },
        ),
    ]
