# Generated by Django 5.1.3 on 2024-11-26 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0007_score'),
        ('judges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='total',
        ),
        migrations.AddField(
            model_name='score',
            name='judge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='judges.judge'),
        ),
    ]
