# Generated by Django 5.1.3 on 2024-11-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0008_remove_score_total_score_judge'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='total',
            field=models.FloatField(default=0.0),
        ),
    ]
