# Generated by Django 5.1.3 on 2024-11-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0009_score_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
