# Generated by Django 5.1.3 on 2024-11-28 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0010_alter_score_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='student_cls',
            field=models.CharField(max_length=20),
        ),
    ]
