# Generated by Django 5.1.3 on 2024-11-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0012_alter_participant_admission_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlifUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'alif_user',
            },
        ),
    ]
