# Generated by Django 5.1.3 on 2024-11-29 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alif_admin', '0013_alifuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='report_status',
            field=models.CharField(default='not reported', max_length=30),
        ),
        migrations.AddField(
            model_name='participant',
            name='report_time',
            field=models.CharField(default='', max_length=30),
        ),
    ]
